### PR TITLE
Table param column_types now accepts and ordered dict

### PR DESCRIPTION
**Pull request by ejmurra**
I got all tests passing in Python3.5 but tox errors out for me so I wasn't able to test in other versions of python.

### CODE REVIEW

**Comment by nbedi** [comment]
Thanks for the pull request! The code looks good but is not handling some use cases. Tests fail when I add an additional case where only some column types are specified. Also I think it's not necessary to use an OrderedDict for this implementation, a standard Python dictionary should do the trick. Let me know if you'd like to make those changes or if we should look into them.

**Comment by ejmurra** [comment]
I'll take another look at it this week and let you know if I get stuck trying to make those changes.

**Comment by ejmurra** [comment]
Okay, the latest commit (https://github.com/ejmurra/agate/commit/5c1d6017ac31f4680beee9a2458587f5e7994ae5) now allows you to pass in a dict rather than an OrderedDict, and also has a test case which doesn't define all the column types. The issue I'm struggling with, and one for which I don't have the solution, is that passing a dict in only works when column names are specified. If column names aren't specified, the dict's keys would need to be letters of the alphabet corresponding to the column that is being assigned a type. This doesn't seem all that intuitive to me, but maybe this is okay? What do you think, @nbedi?

**Comment by nbedi** [comment]
Good point. Column indexes could be more intuitive than letters. We could allow the dict's keys to be ints to specify indexes but if we do that we should probably allow that in TypeTester too. I may merge this in first when I have a chance to look later today and think more on it. 

@onyxfish thoughts on allowing column indexes as keys in TypeTester's force? (scared I'm missing something glaringly wrong about that)

**Comment by nbedi** [comment]
Merged, thanks Eli! Added you to authors.

**Comment by ejmurra** [comment]
Neat, thanks!

**Comment by onyxfish** [comment]
Hey folks, just finally looking over this pull request. I like it! I'm not super-concerned about the edge case where you want to type a column by index. I agree it would make sense, but it seems like the case where you don't have column names AND you want to specify columns types AND you don't want to specify all of them, is fairly unlikely. Also integer keys to dicts can be pretty confusing. Let's leave this as it is now and if somebody has an issue with it we'll open a new ticket.

Thanks for the contribution, Eli!

**Pull request merged**
