### PR TITLE
Initial implementation for Table.pivot. 

### PR DESCRIPTION
**Pull request by nbedi**
Here's my initial implementation for #493. I have this nagging feeling it's not optimal and could be cleaned up but I need to not look at it for a bit. @onyxfish @palewire Any suggestions for cleaning it up or changing usage are appreciated.

### CODE REVIEW

**Comment by palewire** [comment]
Seems like a strong start to me. Here's a couple questions I have:

- So the order of input arguments takes the new computed columns and the group by field for the rows second? I don't know why, but my gut would have reversed that order. No strong argument, but I guess my mind always things 1) Group by this 2) Tally by this.
- Am I reading it right that current this system only supports ``Length`` counts? I of course realize this is only a first draft, but ultimately, I'd like to be able to compute new pivot columns using any of the other compute methods, especially ``Percent``.

**Comment by nbedi** [comment]
I agree with order of arguments feeling more intuitive the other way around. Only have them this way because default arguments have to be after non-default arguments. I could probably work around this somehow.

You are reading `Length` right. I should change it so the count function is an argument that defaults to `Length` but can be specified as something else.

**Comment by nbedi** [comment]
Hmm, struggling to incorporate computations into this implementation. I wanted to apply any given set of computations to the count tables before pivoting them.

But since computations are varied and some wouldn't make sense in this context or even work on the count tables, I'm having trouble doing this properly. It is possible but not intuitive/clean to apply computations after creating the pivoted table (ex: apply percent to each column with a total equal to the sum of all columns). 

Suggestions for the best way to do this would be great.

**Comment by onyxfish** [comment]
So, this is definitely a tricky thing to do. It's one of a couple reasons it doesn't already exist. I think your function signature looks correct. Here is how I think this could be implemented:

* You loop over the pivot columns.
* For each pivot you run a `group_by` on the table, which uses a lambda to group the rows by a tuple of `(keys, pivot_column)`. (Just the current pivot column in the loop.)
* Aggregate the resulting tableset by the appropriate `Computation` (default: `Length`)
* The column of values in the resulting aggregation table is now one column of the final pivot.
* Join together each aggregated table on their common keys.

I *think* this works conceptually. It's probably going to be dog slow, but let's optimize it once we've got it working. Feel like taking another swing at it?

**Comment by onyxfish** [comment]
Had some more thoughts about this: I'm almost certain the above pattern will work. And the reason it works it that `pivot` as we've defined it is just a specific sub-case of the existing `group_by().aggregate()` pattern we've already got. The only difference here is that the user never sees the intermediate tableset and that the resulting columns must all be the same type.

I was originally on the fence about this feature, but now that I've thought it through I see a few of of other standout benefits:

* Given that this is a sub-case, I think it can be optimized as such. I suspect the guts of the `TableSet.aggregate` method could be lifted into pivot and optimized. In particular, there is no possibility of nested TableSet's, so that recursive condition can be removed. (Note: we should wait until it all works before we reimplement that whole method, but if there are major perf wins we'll probably want to.)
* In this case it totally makes sense to automatically populate `row_names` for the resulting output table. That means the resulting table can also function as a 2-dimensional lookup table: `table.rows['white']['male']`
* There is a big memory win here if the user was going to throw away all the intermediate tableset tables anyway.

**Comment by nbedi** [comment]
Will give this another go soon. I'll see if I can get a working implementation from your description and add to the PR so we can look again/optimize.

**Comment by nbedi** [comment]
Still looking and thinking about this because I haven't had time to dive in the code.

Reading your thoughts, I believe the current implementation does most of what you said except some steps are slightly different in implementation.

I still think the issue I had earlier exists. In your step 3, we aggregate by an `Aggregation` (not Computation) where the only one that makes sense is `Length`. We would then need to compute a Computation on top of that if the user wants something like `Percent`. 

From that, the problem is that the inputs to Computations are not standard so using any given `Computation` is tricky. I could get just `Percent` to work but that's a bit ugly. We'd also need to do these Computations on each column which could get slow but not sure if there's a work around for that.

**Comment by onyxfish** [comment]
Okay I think I understand what you're saying now. It's hard to think about these sorts of complex problems without writing code and as it happens I have a need for this feature right at this moment, so let me take a crack at it and see what I can figure out.

**Comment by onyxfish** [comment]
Okay, I see now that my previous pseudo code was solving the wrong problem. (I was only expanding the values in the vertical dimension, not the horizontal one... a much simpler problem.) I still think this is doable. Going to revisit later tonight if I have time.

**Comment by nbedi** [comment]
:+1: let me know if you need anything from me

**Comment by onyxfish** [comment]
Merged in with my revisions. Moving conversation back to #493.

**Pull request closed without merging**
