### PR TITLE
Print bar chart when value column contains nulls

### PR DESCRIPTION
**Pull request by flother**
If the value column contained null values then `agate.Table.print_bars()` would fail with `decimal.InvalidOperation` when trying to convert `None` to a decimal. Now it skips rows with null values in the value column.

If you have a table like this:

Label | Value
------------ | -------------
One | 1
A null value | 
Three | 3

And you run `table.print_bars('label', 'value')`, where previously you would see an error now you see a bar chart with two bars, one for *One*, and one for *Three*.

### CODE REVIEW

**Comment by nbedi** [comment]
Thanks for the pull request! Should the behavior be skipping rows with Null/None values or treating them as 0? Thoughts @flother @onyxfish?

**Comment by flother** [comment]
As long as they're not labelled as zeroes, there's probably a good argument to be made for showing null value labels on a bar chart but leaving the bar itself blank. I'll take another attempt at this.

**Comment by flother** [comment]
If we take [Wikipedia's historical population data for Reykjavík's urban area] (https://en.wikipedia.org/wiki/Reykjav%C3%ADk#Demographics) as an example, my first fix would output a chart like this:

```
Year   Metro
1901   8,221 ▓░░
1910  14,534 ▓░░░
1920  21,347 ▓░░░░
1930  33,867 ▓░░░░░░░
1940  43,483 ▓░░░░░░░░░
1950  44,813 ▓░░░░░░░░░
1960  88,315 ▓░░░░░░░░░░░░░░░░░░
1970 106,152 ▓░░░░░░░░░░░░░░░░░░░░░░
1980 121,698 ▓░░░░░░░░░░░░░░░░░░░░░░░░░
1990 145,980 ▓░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
2000 175,000 ▓░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
2005 187,105 ▓░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
2006 191,612 ▓░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
2007 196,161 ▓░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
2008 201,585 ▓░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
2011 202,341 ▓░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
             +-----------+----------+----------+-----------+
             0        55,000     110,000    165,000  220,000
```

The latest commit means that the null values for 1801, 1860, 1985, and 1995 are part of the chart too, but left blank (with `-` used as a stand-in for the missing data):

```
Year   Metro
1801       - ▓
1860       - ▓
1901   8,221 ▓░░
1910  14,534 ▓░░░
1920  21,347 ▓░░░░
1930  33,867 ▓░░░░░░░
1940  43,483 ▓░░░░░░░░░
1950  44,813 ▓░░░░░░░░░
1960  88,315 ▓░░░░░░░░░░░░░░░░░░
1970 106,152 ▓░░░░░░░░░░░░░░░░░░░░░░
1980 121,698 ▓░░░░░░░░░░░░░░░░░░░░░░░░░
1985       - ▓
1990 145,980 ▓░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
1995       - ▓
2000 175,000 ▓░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
2005 187,105 ▓░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
2006 191,612 ▓░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
2007 196,161 ▓░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
2008 201,585 ▓░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
2011 202,341 ▓░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
2015       - ▓
             +-----------+----------+----------+-----------+
```

**Comment by nbedi** [comment]
Looks great, nice catch and fix. Thanks again!

**Comment by onyxfish** [comment]
Thanks for this, @flother! Looks great!

**Pull request merged**
