### PR TITLE
Add a to_dict method to Table

### PR DESCRIPTION
**Pull request by ToddTurnbull**
I have found it useful to be able to convert a Table to an OrderedDict. These changes extract this functionality from Table.to_json() into a new Table.to_dict() method.

Changes:

1. Added to_dict method to Table
2. Added /tests/test_table/test_to_dict.py
3. Modified Table.to_json() to use to_dict()
4. Added to_dict() to the API documentation

I hope you will consider adding this :)

Cheers,
Todd

### CODE REVIEW

**Comment by ToddTurnbull** [comment]
Alternatively, we could mimic `namedtuple._asdict()`. This might make clear its intent. And I assume it wouldn't show up in the API documentation. I have a branch that changes `to_dict()` to `_asdict()` documented here:

https://github.com/wireservice/agate/compare/master...ToddTurnbull:asdict

**Comment by nbedi** [comment]
Thanks for the pull request!

I like the idea of a `to_dict` method, especially to mirror the recently added [`from_object`](https://github.com/wireservice/agate/blob/master/agate/table/from_object.py) method. It may be nice to call it `to_object` for consistency and [mimic the format](https://github.com/wireservice/agate/blob/master/agate/table/from_object.py#L14-L38) `from_object` uses to import an entire table (I believe your current implementation would only export a column/column func).

I also think `to_object` should return a Python object by default but have an option to return an OrderedDict to preserve order.

Let me know what you think and if you have the time to make those changes. Thanks again!

**Comment by onyxfish** [comment]
This is great. Echoing @nbedi, I think it should be `to_object` for consistency. I would be fine with it always returning an `OrderedDict` since it is API compatible with the standard `dict`. (@nbedi if you have a reason in mind this is a bad idea, let me know.)

**Comment by nbedi** [comment]
@onyxfish Nope that sounds fine! I totally forgot it was API compatible.

**Comment by Kirkman** [comment]
Don't know if there's hope for this idea to be resurrected, but I for one would love to be able to turn an agate table into a dict.

**Comment by jpmckinney** [comment]
You can open an issue or start a PR based on the discussion here. I just didn’t see this PR being completed after 3 years.

**Pull request closed without merging**
