### PR TITLE
Reimplement slugify with python-slugify

### PR DESCRIPTION
**Pull request by nbedi**
#660, #615

### CODE REVIEW

**Comment by nbedi** [comment]
@onyxfish This should work other than the case in #615. Let me know what you think when you have free time. (sorry for bombarding your mentions the past couple of days)

**Comment by Jenselme** [comment]
Any updates on this?

**Comment by nbedi** [comment]
@Jenselme sorry for the delay, I think we both are a bit caught up with work and this is turning out to be part of a breaking change so it'll take some review. I believe I've smoothed out some edges now, so we're getting closer.

**Comment by Jenselme** [comment]
@nbedi thanks for you updates. No hurries ;-)

**Comment by onyxfish** [comment]
@nbedi This looks great. I've merged it in.

**Pull request merged**
